# Generated by Django 6.0.3 on 2026-03-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('memory', models.CharField(blank=True, max_length=200, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_current', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('characteristics', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
